version: '3'
services:

  pydio:
    image : pydio
    container_name: pydio
    hostname: pydio
    build: .
    restart: always
    tty: true
    ports:
      - 2345:80
      - 6789:443
    links:
      - database
    volumes:
      - pydiofiles:/var/www/pydio/data/files/
      - pydiopersonal:/var/www/pydio/data/personal
  database:
    image: mariadb:latest
    restart: always
    hostname: database
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: pydio
      MYSQL_DATABASE: pydio
    volumes:
      - mysqldata:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    container_name: phpminiadmin
    ports:
      - 8080:8080

volumes:
  mysqldata:
  pydiopersonal:
  pydiofiles:
