version: '3'
services:

  pydio:
    image : pydio-test
    container_name: pydio
    build: .
    restart: always
    tty: true
    ports:
      - 2345:80
      - 6789:443
    links:
      - db
    volumes:
      - pydiofiles:/var/www/pydio/data/files/
      - pydiopersonal:/var/www/pydio/data/personal
  db:
    image: mariadb
    restart: always
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: pydio
      MYSQL_DATABASE: pydio
    volumes:
      - mysqldata:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    container_name: phpminiadmin
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data

volumes:
  redisdata:
  mysqldata:
  pydiopersonal:
  pydiofiles:
  esdata1:
  esdata2: