version: '3'
services:

  pydio:
    image : zayn/pydio-community
    container_name: pydio
    restart: always
    hostname: pydio-com
    tty: true
    ports:
      - 443:443
    links:
      - db
    volumes:
      - pydiofiles:/var/www/pydio/data/files/
      - pydiopersonal:/var/www/pydio/data/personal
  db:
    image: mariadb
    restart: always
    hostname: mariadb
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: pydio
      MYSQL_DATABASE: pydio
    volumes:
      - mysqldata:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    container_name: phpminiadmin
    ports:
      - 8080:8080

  redis:
    image: redis
    hostname: redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

volumes:
  redisdata:
  mysqldata:
  pydiopersonal:
  pydiofiles:
